--Query One
INSERT INTO account (account_firstname, account_lastname, account_email, account_password) VALUES ('Tony', 'Stark', 'tony@starkent.com', 'Iam1ronM@n');

--Query Two
UPDATE account SET account_type = "Admin" WHERE account_lastname = 'Stark';

--Query Three
DELETE account WHERE account_firstname = 'Tony';

--Query Four
SELECT * FROM inventory
Replace ("Do you have 6 kids and like to go offroading? The Hummer gives you the small interiors with an engine to get you out of any muddy or rocky situation", "small", "huge");

--Query Five
SELECT inv_model, inv_make, classification_name
FROM inventory i
INNER JOIN classification ON i.classification_id = classification.classification_id
WHERE classification_name = 'Sport';

--Query Six
UPDATE inventory
SET inv_image = REPLACE(inv_image, '/images/', '/image/vehicles');
UPDATE inventory
SET inv_thumbnail = REPLACE(inv_thumbnail, '/images/', '/image/vehicles');



--Create Reviews Table
CREATE TABLE IF NOT EXISTS reviews
(	review_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	review_text character varying NOT NULL,
	review_date date NOT NULL,
	inv_id integer NOT NULL,
	account_id integer NOT NULL
);

--Create Relationship between "accounts" and "inventory" tables
ALTER TABLE IF EXISTS reviews
	ADD CONSTRAINT fk_inventory FOREIGN KEY (inv_id)
	REFERENCES inventory(inv_id) MATCH SIMPLE
	ON UPDATE CASCADE
	ON DELETE NO ACTION;

ALTER TABLE IF EXISTS reviews		
	ADD CONSTRAINT fk_account FOREIGN KEY (account_id)
	REFERENCES account (account_id) MATCH SIMPLE
	ON UPDATE CASCADE
	ON DELETE NO ACTION;